INSERT INTO USER_ROLE (ID, ROLE_NAME) VALUES (1, "ADMIN");
INSERT INTO USER_ROLE (ID, ROLE_NAME) VALUES (2, "USER");
INSERT INTO USERS (USER_ID, PASSWORD, VERIFIED, ROLE_ID) VALUES (123456, "Password1", 1, 1);